---
label: Config
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: select
  name: palette
  label: Color Palette
  description: The color palette used in the theme
  config:
    required: true
    source:
      type: custom
    options:
    - blue
    - magenta
    - purple
- type: field_group
  name: palettes
  label: Palettes
  hidden: true
  fields:
  - type: field_group
    name: blue
    label: Blue
    fields:
    - type: include
      name: include_palette
      label: Palette
      template: palette
  - type: field_group
    name: magenta
    label: Magenta
    fields:
    - type: include
      name: include_palette
      label: Palette
      template: palette
  - type: field_group
    name: purple
    label: Purple
    fields:
    - type: include
      name: include_palette
      label: Palette
      template: palette
